version: "3"
services:
  db:
    image: postgres:latest
    restart: always
    container_name: book_notes-dart_server-postgre_test
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ../../db/structure.sql:/docker-entrypoint-initdb.d/structure.sql
volumes:
  db:
    driver: local