version: "3"
services:
  db:
    image: postgres:latest
    restart: always
    container_name: book_notes-dart_server-postgre_test
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ../../db/structure.sql:/docker-entrypoint-initdb.d/structure.sql
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
volumes:
  db:
    driver: local
