name: book_notes
description: A simple command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  shelf: ^1.3.0
  postgres: ^2.4.3

dev_dependencies:
  lints: ^1.0.0
  test: ^1.21.1
